// src/components/DetailsItem.vue

<script setup lang="ts">
import { computed, toRefs } from 'vue';

type DetailsItem = {
    type: "website" | "phone" | "email" | "data",
    label?: string,
    domain?: string,
};
const props = defineProps<DetailsItem>();
const { type, domain, label } = toRefs(props);

const types = {
    website: ["https", "ex"],
    phone: ["tel", "in"],
    email: ["mailto", "in"],
    data: [undefined, "none"],
};

const linkAttrs = computed(() => {
    const [protocol, className] = types[type.value];
    const href = protocol ? `${protocol}:${domain.value}` : undefined;
    const target = type.value === "website" ? "_blank" : undefined;

    return {
        class: `link--${className}`,
        href,
        target,
    };
});
</script>

<template>
    <div><a v-bind="linkAttrs">{{ label }}</a></div>
</template>

// src/components/Details/DetailsItem.tsx
import { useMemo } from "react";

type DetailsItem = {
    type: "website" | "phone" | "email" | "data" | string;
    label?: string;
    domain?: string;
};
type DetailsProps = DetailsItem;

const DetailsItem: React.FC<DetailsProps> = ({ type, domain, label }) => {
    const linkAttrs = useMemo(() => {
        const types = {
            website: ["https", "ex"],
            phone: ["tel", "in"],
            email: ["mailto", "in"],
            data: [undefined, "none"],
        };
        const [protocol, className] = types[type];
        const href = protocol ? `${protocol}:${domain}` : undefined;
        const target = type === "website" ? "_blank" : undefined;

        return {
            className: `link--${className}`,
            href,
            target,
        };
    }, [domain, type]);

    return (
        <div><a {...linkAttrs}>{label}</a></div>
    );
};

export default DetailsItem;
