// src/components/Details/Details.tsx
import DetailsItem from "./DetailsItem";
import styles from "./details.module.stylus";

type DetailsProps = {
    title: string;
    links: Array<DetailsItem>;
};

const Details: React.FC<DetailsProps> = ({ title, links }) => {
    return (
        <section className="section section--aside">
            <h2 className="section__title">{title}</h2>
            <ul className={styles.items}>
                {links.map((link, i) => (
                    <li key={i}>
                        <DetailsItem {...link} />
                    </li>
                ))}
            </ul>
        </section>
    );
};

export default Details;

// src/main/components/Details.vue
<script lang="tsx" setup>
import { useCssModule } from "vue";
import { useContent } from "../composables/useContent";
import DetailsItem from "./DetailsItem.vue";

const classes = useCssModule();
const content = useContent();

function render() {
    const { title, links } = content.value.body.details;

    return (
        <div class="section section--aside">
            <h2 class="section__title">{ title }</h2>
            <nav>
                <ul class={classes.items}>
                    { links.map((o) => <DetailsItem {...o}/>) }
                </ul>
            </nav>
        </div>
    );
}
</script>

<template><render/></template>

<style module lang="stylus">
.items {
    li {
        line-height: 1.2;
    }    
}
</style>
