// src/layouts/PageLayout/FooterLink.tsx
import React, { useMemo } from "react";
import styles from "./footer.module.stylus";
import { formatPhone } from "../../utils/format";

export type ILink = { href: string, value: string };

type FooterLinkProps = {
    label: string;
    obj: ILink;
};

const FooterLink: React.FC<FooterLinkProps> = ({ label, obj }) => {
    const link = useMemo(() => {
        const anchorTypes = {
            "mailto:": "in",
            "https:": "ex",
            "tel:": "in",
        };

        const { href, value } = obj;
        const protocol = new URL(href).protocol;
        const anchorType = anchorTypes[protocol] || "none";

        const attrs = {
            href,
            target: "_blank",
            className: `${styles.link__a} link--${anchorType}`,
        };

        return {
            attrs,
            value: protocol === "tel:" ? formatPhone(value) : value,
        };
    }, [obj]);
    const linkId = `footer-link-${btoa(label)}`;

    return (
        <div className={styles.link}>
            <label className={styles.link__label} htmlFor={linkId}>{label}</label>
            <a {...link.attrs} id={linkId}>{link.value}</a>
        </div>
    )
}

export default FooterLink;

// src/main/components/FooterLink.vue
<script lang="tsx" setup>
import { formatPhone } from "../helpers/formatPhone";

const props = defineProps<{
    label: string,
    obj: any,
}>();

function render() {
    const label = props.label;
    let { value, href } = props.obj;

    const protoc = new URL(href).protocol;
    value = protoc === "tel:" ? formatPhone(value) : value;
    
    const anchorTypes = {
        "mailto:": "in",
        "https:": "ex",
        "tel:": "in",
    };
    const anchorType = anchorTypes[protoc] || "none";

    const linkAttrs = {
        href,
        target: "_blank",
        class: `footer-link__a link--${anchorType}`,
    };

    return (
        <div class="footer-link">
            <div class="footer-link__label">{ label }</div>
            <a {...linkAttrs}>{ value }</a>
        </div>
    );
}
</script>

<template><render/></template>
