// src/layouts/PageLayout/Footer.tsx
import React, { useMemo } from "react";
import styles from "./footer.module.stylus";
import luisfloatLogo from "/logos/luisfloat/luisfloat-logo-light.png";
import FooterLink from "./FooterLink";
import moment from "moment";
import { IGeneration } from "./PageLayout";

type FooterProps = {
    links: Record<"string", { href: string, value: string }>;
    generation: IGeneration;
};

const Footer: React.FC<FooterProps> = ({ links, generation }) => {
    const linkAttrs = (key: string) => ({ label: key, obj: links[key] });
    
    const generatedTime = useMemo(() => {
        moment.locale(generation.locale);
        return moment().format(generation.timeFormat);
    }, [generation]);

    return (
        <footer className="section section--footer">
            <ul className={styles.links}>
                {Object.keys(links).map((key, i) => (
                    <li key={i}>
                        <FooterLink {...linkAttrs(key)} />
                    </li>
                ))}
            </ul>
            <div className={styles.logo} >
                <img className={styles.logo__image} src={luisfloatLogo} alt="Logo" />
            </div >
            <div className={styles.generation} >
                <div className={styles.generation__text} data-content={generation.text + generatedTime} />
            </div>
        </footer>
    )
}

export default Footer;

// src/main/components/Footer.vue
<script lang="tsx" setup>
import { useCssModule } from "vue";
import { useContent } from "../composables/useContent";
import FooterLink from "./FooterLink.vue";
import moment from "moment";

const classes = useCssModule();
const content = useContent();

function render() {
    const body = content.value.body;
    const { generation, links } = body?.footer;

    const linkAttrs = (k: string) => ({ label: k, obj: links[k] });

    moment.locale(generation.locale);
    const generatedTime = moment().format(generation.timeFormat);

    return (
        <div class="section section--footer">
            <div class={classes.links}>
                {Object.keys(links).map((k: string) => <FooterLink {...linkAttrs(k)}/>)}
            </div>
            <div class={classes.logo}>
                <img class={classes.logo__image} src="assets/img/logo.png" alt="Logo" />
            </div>
            <div class={classes.generation}>
                <div
                    class={classes.generation__text}
                    data-content={generation.text + generatedTime}>
                </div>
            </div>
        </div>
    );
}
</script>

<template><render/></template>

<style module lang="stylus">
.links {
    width: 100%;
    z-index: 1;
}

.logo {
    height: 100%;
    display: flex;
    align-items: center;

    &__image {
        width: 1.38cm;
        height: 1.38cm;
    }
}

.generation {
    display: none;
    position: absolute;
    
    @media print {
        display: block;
    }

    &__text::after {
        position: relative;
        content: attr(data-content);
        width: 100%;
        height: 100%;
        z-index: 200;
        bottom: -60px;
        left: 0;
        font-size: 9pt;
        color: color-gray-6;
    }
}
</style>
