// src/components/Header/Header.tsx
import { ComponentProps } from "react";
import styles from "./header.module.stylus";

type HeaderProps = {
    title: string;
    description: string;
} & ComponentProps<"header">;

const Header: React.FC<HeaderProps> = ({ title, description, ...props }) => {
    return (
        <header className="section" {...props}>
            <h1 className="section__title section__title--header">{title}</h1>
            <div className={styles.description}>{description}</div>
        </header>
    );
};

export default Header;

// src/main/components/Header.vue
<script lang="tsx" setup>
import { useContent } from '../composables/useContent';

const content = useContent();

function render() {
    const { title, description } = content.value.body?.header;

    return (
        <div class="section section--header">
            <h1 class="section__title section__title--header">{ title }</h1>
            <div class="header__description">{ description }</div>
        </div>
    );
}
</script>

<template><render/></template>
