// src/components/Skills/Skills.tsx
import HorizontalList from "../HorizontalList/HorizontalList";
import styles from "./skills.module.stylus";

type SkillsProps = {
    title: string;
    separator?: string;
    hard1: Array<string>;
    hard2: Array<string>;
    soft1: Array<string>;
    soft2: Array<string>;
};

const Skills: React.FC<SkillsProps> = ({ title, separator, hard1, hard2, soft1, soft2 }) => {
    return (
        <section className="section section--aside">
            <h2 className="section__title">{title}</h2>
            <div className={styles.skills}>
                <HorizontalList items={hard1} separator={separator} type="primary" />
                <HorizontalList items={hard2} separator={separator} type="normal" />
                <HorizontalList items={soft1} separator={separator} type="normal" />
                <HorizontalList items={soft2} separator={separator} type="primary" />
            </div>
        </section>
    );
};

export default Skills;

// src/main/components/Skills.vue
<script lang="tsx" setup>
import { useContent } from "../composables/useContent";
import VBarList from "./VBarList.vue";

const content = useContent();

function render() {
    const body = content.value.body;
    const { title, hard1, hard2, soft1, soft2 } = body?.skills;
    const sep = body?.skills?.sep;

    return (
        <div class="section section--aside">
            <h2 class="section__title">{ title }</h2>
            <VBarList items={hard1} sep={sep} type="primary"/>
            <VBarList items={hard2} sep={sep} type="normal"/>
            <VBarList items={soft1} sep={sep} type="normal"/>
            <VBarList items={soft2} sep={sep} type="primary"/>
        </div>
    );
}
</script>

<template><render/></template>

<style module lang="stylus">
.skills {
    &__hard-name {
        color: color-azure-4;
    }
}
</style>
