// src/components/Details/Details.tsx
import DetailsItem from "./DetailsItem";
import styles from "./details.module.stylus";

type DetailsProps = {
    title: string;
    links: Array<DetailsItem>;
};

const Details: React.FC<DetailsProps> = ({ title, links }) => {
    return (
        <section className="section section--aside">
            <h2 className="section__title">{title}</h2>
            <ul className={styles.items}>
                {links.map((link, i) => (
                    <li key={i}>
                        <DetailsItem {...link} />
                    </li>
                ))}
            </ul>
        </section>
    );
};

export default Details;

// src/components/Details.vue
<script setup lang="ts">
import { useCssModule } from "vue";
import { useContent } from "../composables/useContent";
import DetailsItem from "./DetailsItem.vue";

const classes = useCssModule();
const details = useContent(s => s.body.details);
</script>

<template>
    <div class="section section--aside">
        <h2 class="section__title">{{ details.title }}</h2>
        <nav>
            <ul :class="classes.items">
                <DetailsItem v-for="link in details.links" v-bind="link" />
            </ul>
        </nav>
    </div>
</template>

<style module lang="stylus">
.items {
    li {
        line-height: 1.1;
    }    
}
</style>
