// src/components/Header/Header.tsx
import { ComponentProps } from "react";
import styles from "./header.module.stylus";

type HeaderProps = {
    title: string;
    description: string;
} & ComponentProps<"header">;

const Header: React.FC<HeaderProps> = ({ title, description, ...props }) => {
    return (
        <header className="section" {...props}>
            <h1 className="section__title section__title--header">{title}</h1>
            <div className={styles.description}>{description}</div>
        </header>
    );
};

export default Header;

// src/components/Header.vue
<script setup lang="ts">
import { useCssModule } from 'vue';
import { useContent } from '../composables/useContent';

const classes = useCssModule();
const content = useContent(s => s.body.header);
</script>

<template>
    <div class="section section--header">
        <h1 class="section__title section__title--header">{{ content.title }}</h1>
        <div :class="classes.description">{{ content.description }}</div>
    </div>
</template>

<style module lang="stylus">
.description {
    font-weight: 400;
    font-size: 10pt;
    color: color-gray-4;

    margin-top: 2pt !important;
    margin-bottom: 10pt !important;
}
</style>
